### ISSUE TITLE
Can't set badge style

### ISSUE THREAD

**Issue by Jengas** [XMGamingMaster/RageMP-NativeUI#10]
When trying to set any badge to menu
`var x = new UIMenuItem("Text1", "Text2");
x.SetLeftBadge("GoldMedal")`
In result gives this error:
![image](https://user-images.githubusercontent.com/14033756/49740167-f116de80-fc93-11e8-94f7-4ffa7e907933.png)

**Comment by omermecitoglu** [comment]
`SetLeftBadge(BadgeStyle.GoldMedal)`
