### ISSUE TITLE
BindMenuToItem bug

### ISSUE THREAD

**Issue by omermecitoglu** [XMGamingMaster/RageMP-NativeUI#4]
Let's say you have a **main** menu and it has a **child** and a **grandchild** menus;
First, go to **grandchild** and then go back to **main** menu.
After that if you try to use the menuitem which is bound to **child**, it redirects you to **grandchild** instead of **child** menu

**Comment by SNIKRS** [comment]
Yeah +1 i figured this out yesterday

**Comment by SNIKRS** [comment]
even if u do this 
if(ui.Visible == true)
{
	ply.Visible = false;
	vehicle.Visible = false;
}
the bug is still there

**Comment by stevenmodl** [comment]
I will look into that!
